
language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
solution: ./RepositoryPattern.SQLite.sln
notifications:
  email: false
before_install:
  - git lfs pull
install:
  - dotnet restore
script:
  - dotnet restore
  - cd tests/
  - dotnet test
  